language: perl
perl:
  - "5.18-extras"
before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
install:
  - sudo apt-get install libdbus-1-dev
  - cpanm -nq --installdeps .
  - sudo apt-get install libopencv-dev libtheora-dev libcv-dev libhighgui-dev tesseract-ocr
script:
  - find . -type f | xargs -n1 sed -i -e 's,#!/usr/bin/perl,#!/usr/bin/env perl,'
  - sh autogen.sh 
  - ./configure
  - make && make check VERBOSE=1

