language: perl
perl:
  - "5.18-extras"
before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
install:
  - cpanm -nq Perl::Tidy
  - sudo apt-get install libopencv-dev libtheora-dev libcv-dev libhighgui-dev libdata-dump-perl libjson-perl libcarp-always-perl tesseract-ocr
script:
  - ./tools/tidy --check
  - sh autogen.sh 
  - ./configure
  - make && make check

