dist: trusty
language: perl
perl:
  - "5.18-extras"
install:
  - SETUP_FOR_TRAVIS=1 sh autogen.sh
script:
  # 'coverage' executes all tests and checks code coverage against threshold
  # in Makefile.am
  - make && make check coverage-coveralls VERBOSE=1
sudo: required
