---
name: Author tests

on: [push, pull_request]

jobs:
  author-tests:
    runs-on: ubuntu-latest
    name: Author tests
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@v4
      - name: make test-local
        run: |
          git config --global --add safe.directory '*'
          make
          # see .github/workflows/commit-message-checker.yml
          # for the git commit message check
          ctest --output-on-failure -R "test-local-.*" -E "test-local-git-commit-message"
