---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
env:
  # Set to 1 to temporarily ignore warnings
  PERL_TEST_WARNINGS_ONLY_REPORT_WARNINGS: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Static checks, unit- and integration tests
        run: tools/container_run_ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # should not be necessary for public repos, but might help avoid sporadic upload token errors
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
      - run: |
          tar cvf coverage.tar build/cover_db
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.tar
          retention-days: 15
  static-check-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test our container definitions
        run: tools/static_check_containers
